<?php
/**
 * @file
 * nyc_camp_job_openings.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function nyc_camp_job_openings_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'Sample Job Title',
  'log' => '',
  'status' => 0,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '7e6471cc-e276-437c-aae1-0cef911f2d08',
  'ds_switch' => '',
  'type' => 'job',
  'language' => 'und',
  'created' => 1396501880,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '250bfc68-5cbd-4a48-b4af-e6736af6e406',
  'revision_uid' => 307,
  'field_job_additional_info' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Additional info.</p>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>Additional info.</p>
',
      ),
    ),
  ),
  'field_job_deadline' => array(
    'und' => array(
      0 => array(
        'value' => '2014-04-03 00:00:00',
        'timezone' => 'America/New_York',
        'timezone_db' => 'America/New_York',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_job_description' => array(
    'und' => array(
      0 => array(
        'value' => '<p>This is a job description</p>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>This is a job description</p>
',
      ),
    ),
  ),
  'field_job_education' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Desired education</p>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>Desired education</p>
',
      ),
    ),
  ),
  'field_job_experience' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Job Experience</p>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>Job Experience</p>
',
      ),
    ),
  ),
  'field_job_pdf' => array(),
  'field_job_responsibilities' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Job Responsibilities can be listed here.</p>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>Job Responsibilities can be listed here.</p>
',
      ),
    ),
  ),
  'field_job_salary' => array(
    'und' => array(
      0 => array(
        'value' => '<p>A full-text area where you can list salary ("$500,000!...") and give more details ("...Contingent on working 120 hours per week.")</p>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>A full-text area where you can list salary ("$500,000!...") and give more details ("...Contingent on working 120 hours per week.")</p>
',
      ),
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'NYC Camp',
  'picture' => 919,
  'data' => 'a:9:{s:7:"contact";i:0;s:7:"overlay";i:1;s:8:"gravatar";i:1;s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";s:18:"htmlmail_plaintext";i:0;}',
  'weight_weight' => FALSE,
  'date' => '2014-04-03 01:11:20 -0400',
);
  $nodes[] = array(
  'uid' => 1935,
  'title' => 'PHP-WordPress Developer',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'faed9049-dfc7-4e01-8ed6-55a8c2866d2c',
  'ds_switch' => '',
  'type' => 'job',
  'language' => 'und',
  'created' => 1396985960,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '7122c9c9-ccd4-401a-9d15-d629dbc8b4a7',
  'revision_uid' => 1935,
  'field_job_additional_info' => array(),
  'field_job_deadline' => array(
    'und' => array(
      0 => array(
        'value' => '2014-06-02 00:00:00',
        'timezone' => 'America/New_York',
        'timezone_db' => 'America/New_York',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_job_description' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Job Title: PHP/WordPress Developer Location: NYC - midtown Job Type: Contract Duration: 6 months + Contact Info: Eileen Hannon - ehannon@techlink.com - 201-786-2417 *Only want candidates eligible for hire should they decide they want to make a perm offer. Requirements: • Our direct client in the media industry is in need of a PHP/Wordpress Developer with MySQL. • VIP experience preferred as well as someone out of a news organization.</p>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>Job Title: PHP/WordPress Developer Location: NYC - midtown Job Type: Contract Duration: 6 months + Contact Info: Eileen Hannon - ehannon@techlink.com - 201-786-2417 *Only want candidates eligible for hire should they decide they want to make a perm offer. Requirements: • Our direct client in the media industry is in need of a PHP/Wordpress Developer with MySQL. • VIP experience preferred as well as someone out of a news organization.</p>
',
      ),
    ),
  ),
  'field_job_education' => array(),
  'field_job_experience' => array(),
  'field_job_pdf' => array(),
  'field_job_responsibilities' => array(),
  'field_job_salary' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1935,
  'comment_count' => 0,
  'name' => 'MattyRecruiter',
  'picture' => 0,
  'data' => 'a:7:{s:7:"contact";i:1;s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";s:18:"htmlmail_plaintext";i:0;}',
  'weight_weight' => FALSE,
  'date' => '2014-04-08 15:39:20 -0400',
);
  return $nodes;
}
