<?php
/**
 * @file
 * nyc_camp_partners.features.uuid_commerce_product.inc
 */

/**
 * Implements hook_uuid_features_default_commerce_product().
 */
function nyc_camp_partners_uuid_features_default_commerce_product() {
  $products = array();

  $products[] = array(
  'sku' => '2015_silver',
  'title' => 'Silver Partnership',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => '6919aec4-04fe-4f7b-920e-b77ade69e344',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533431,
  'uuid' => '11ed7856-61d5-416c-a278-b2add3c4226f',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 250000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Tier Partnership',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Medium logo on Partners Page and rotating promo block on all page',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Medium Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Medium Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'SmallDaily combined thanks on Twitter/Facebook
Small Logo in the footer of every communication email Table',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Daily combined thanks on Twitter/Facebook
Small Logo in the footer of every communication email',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Solo on-screen and combined verbal thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '15.00',
      ),
    ),
  ),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'ce95b3e7-fce0-4d6a-b39f-79ed7932ae76',
);
  $products[] = array(
  'sku' => '2015_bof',
  'title' => 'BoF Partner',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => '6b9c8911-533e-44d4-8133-65280f1116ee',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533682,
  'uuid' => '58bfb695-dc76-4129-8250-3c8645b72c8e',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 50000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Other Title Partnership',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Small logo on Partners Page and rotating promo block on some pages',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks (Session Day) on Twitter/Facebook	',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Combined on-screen thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '0.00',
      ),
    ),
  ),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'ce95b3e7-fce0-4d6a-b39f-79ed7932ae76',
);
  $products[] = array(
  'sku' => '20015_bronze',
  'title' => 'Bronze Partnership',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => '3b34ffe8-f328-48cc-b129-8621f82a4d85',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533511,
  'uuid' => '6ca137f3-cd61-45f6-b76a-2dc01c562598',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 100000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Tier Partnership',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Small logo on Partners Page and rotating promo block on all pages',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Materials displayeed on shared table (materials only, no staff/people)',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks (Session Day) on Twitter/Facebook',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Combined verbal thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '10.00',
      ),
    ),
  ),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'ce95b3e7-fce0-4d6a-b39f-79ed7932ae76',
);
  $products[] = array(
  'sku' => '2015_community',
  'title' => 'Community Partnership',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => '15c7446a-ba6e-42fc-881f-d70868c38d72',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533586,
  'uuid' => '6e6d9df9-45c1-4506-81da-24e13f0fdad4',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 35000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Tier Partnership',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Small logo on Partners Page and rotating promo block on all pages',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Materials displayeed on shared table (materials only, no staff/people',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks (Session Day) on Twitter/Facebook',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Combined verbal thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '20.00',
      ),
    ),
  ),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'ce95b3e7-fce0-4d6a-b39f-79ed7932ae76',
);
  $products[] = array(
  'sku' => '2015_party',
  'title' => 'Evening Party Partner',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => '5fff1ecf-e20f-44e0-9564-e5e52f0ef780',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425534007,
  'uuid' => '8b5d4297-f121-46e2-b53a-853cc555cbb1',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 50000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Other Title Partnership',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Small logo on Partners Page and rotating promo block on some pages',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks (Session Day) on Twitter/Facebook',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Combined on-screen thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '1.00',
      ),
    ),
  ),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'ce95b3e7-fce0-4d6a-b39f-79ed7932ae76',
);
  $products[] = array(
  'sku' => '2015_community_workshop',
  'title' => 'Community Tools Workshop Partner',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => 'e9f786fd-eb3d-46a7-a9b2-572b9991e6c1',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533771,
  'uuid' => 'b128b343-e49a-444c-b7d9-df153d3b2b39',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 50000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Other Title Partnership',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Small logo on Partners Page and rotating promo block on some pages',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks (Session Day) on Twitter/Facebook',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Combined on-screen thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '1.00',
      ),
    ),
  ),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'ce95b3e7-fce0-4d6a-b39f-79ed7932ae76',
);
  $products[] = array(
  'sku' => '2015_daycare',
  'title' => 'Daycare Partner',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => 'dadc49ba-eb93-4dfe-86da-d7e4d8678cbc',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533937,
  'uuid' => 'b6d41141-d8c0-4e7a-81cc-bfdc8ee027c2',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 50000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Other Title Partnership',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Small logo on Partners Page and rotating promo block on some pages',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks (Session Day) on Twitter/Facebook',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Combined on-screen thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '1.00',
      ),
    ),
  ),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'ce95b3e7-fce0-4d6a-b39f-79ed7932ae76',
);
  $products[] = array(
  'sku' => '2015_gold',
  'title' => 'Gold Partnership',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => '388823cc-7bdf-4abe-907d-49d44067d75a',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533316,
  'uuid' => 'd6009009-36cb-4c27-9408-d462ddb78a9d',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 500000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Tier Partnership',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Large logo on Partners Page and footer promo on landing pages',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Large Logo, Inside Back Cover',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Large Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Medium Table',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks - Saturday
Solo thanks (Session Day) and daily combined thanks on Twitter/Facebook
Medium Logo in the footer of every communication email',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Solo on-screen and combined verbal thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Recognition (via tweets, verbal, in program, and small signage) for coffee break food service',
        'format' => NULL,
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '5.00',
      ),
    ),
  ),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'ce95b3e7-fce0-4d6a-b39f-79ed7932ae76',
);
  $products[] = array(
  'sku' => '2015_lead',
  'title' => 'Lead Partnership',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => 'a66a27b6-1315-4a09-afea-949433263d77',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425531766,
  'uuid' => 'd7b20de7-5f61-4251-9003-775278b67a3b',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 800000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Tier Partnership',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'X-Large logo on Partners Page and footer promo on all pages',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'X-Large Logo, Inside Cover',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'X-Large Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Large Table
Reservable Private Breakout Room',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Daily solo and combined thanks
Solo thanks (Saturday) and daily combined thanks
Daily combined thanks
Single combined thanks - Saturday',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Solo verbal and on-screen thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Recognition (via tweets, verbal, in program, and small signage) for breakfast and lunch food service',
        'format' => NULL,
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '5.00',
      ),
    ),
  ),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'ce95b3e7-fce0-4d6a-b39f-79ed7932ae76',
);
  $products[] = array(
  'sku' => '2015_coder_lounge',
  'title' => 'Chx Coder Lounge Partner',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => 'e09ddff3-ba41-4703-a8bb-ff365896c8fc',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533859,
  'uuid' => 'dcc059ec-fff7-4fc0-89a6-57145166ff82',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 50000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Other Title Partnership',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Small logo on Partners Page and rotating promo block on some pages',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks (Session Day) on Twitter/Facebook',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Combined on-screen thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '1.00',
      ),
    ),
  ),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'ce95b3e7-fce0-4d6a-b39f-79ed7932ae76',
);
  return $products;
}
