<?php
/**
 * @file
 * nyc_camp_partners.features.uuid_commerce_product.inc
 */

/**
 * Implements hook_uuid_features_default_commerce_product().
 */
function nyc_camp_partners_uuid_features_default_commerce_product() {
  $products = array();

  $products[] = array(
  'sku' => '2015_tier_silver',
  'title' => 'Silver Partnership',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => '27c8793e-5838-4c05-91ea-1ec5b65cc154',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533431,
  'uuid' => '11ed7856-61d5-416c-a278-b2add3c4226f',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 250000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '15.00',
      ),
    ),
  ),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Solo on-screen and combined verbal thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'SmallDaily combined thanks on Twitter/Facebook
Small Logo in the footer of every communication email Table',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Medium Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Medium Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Daily combined thanks on Twitter/Facebook
Small Logo in the footer of every communication email',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Tier Partnership',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Medium logo on Partners Page and rotating promo block on all page',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'f7753eb0-af07-4b3c-9af4-416bf29c5c04',
);
  $products[] = array(
  'sku' => '2015_other_bofs',
  'title' => 'BoFs Partner',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => 'c94da04b-36b0-453e-ae14-ebc2b5a5a85a',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533682,
  'uuid' => '58bfb695-dc76-4129-8250-3c8645b72c8e',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 50000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '0.00',
      ),
    ),
  ),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Combined on-screen thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks (Session Day) on Twitter/Facebook	',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Other Title Partnership',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Small logo on Partners Page and rotating promo block on some pages',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'f7753eb0-af07-4b3c-9af4-416bf29c5c04',
);
  $products[] = array(
  'sku' => '2015_tier_bronze',
  'title' => 'Bronze Partnership',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => '2de612f9-c4e2-4813-a0b7-63d4a0c31a56',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533511,
  'uuid' => '6ca137f3-cd61-45f6-b76a-2dc01c562598',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 100000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '10.00',
      ),
    ),
  ),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Combined verbal thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Materials displayeed on shared table (materials only, no staff/people)',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks (Session Day) on Twitter/Facebook',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Tier Partnership',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Small logo on Partners Page and rotating promo block on all pages',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'f7753eb0-af07-4b3c-9af4-416bf29c5c04',
);
  $products[] = array(
  'sku' => '2015_tier_community',
  'title' => 'Community Partnership',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => '4fb19abd-31ee-4a1d-bd10-c6af90b0db42',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533586,
  'uuid' => '6e6d9df9-45c1-4506-81da-24e13f0fdad4',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 35000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '20.00',
      ),
    ),
  ),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Combined verbal thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Materials displayeed on shared table (materials only, no staff/people',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks (Session Day) on Twitter/Facebook',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Tier Partnership',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Small logo on Partners Page and rotating promo block on all pages',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'f7753eb0-af07-4b3c-9af4-416bf29c5c04',
);
  $products[] = array(
  'sku' => '2015_party_saturday',
  'title' => 'Saturday Evening Party Partner',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => '747e9c08-9f26-423d-8257-98d85d7ce724',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425534007,
  'uuid' => '8b5d4297-f121-46e2-b53a-853cc555cbb1',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 100000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '1.00',
      ),
    ),
  ),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Combined on-screen thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks (Session Day) on Twitter/Facebook',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Other Title Partnership',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Small logo on Partners Page and rotating promo block on some pages',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'f7753eb0-af07-4b3c-9af4-416bf29c5c04',
);
  $products[] = array(
  'sku' => '2015_other_community_workshop',
  'title' => 'Community Tools Workshop Partner',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => 'c057ea1f-2784-4f79-90b5-9d031528c3a4',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533771,
  'uuid' => 'b128b343-e49a-444c-b7d9-df153d3b2b39',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 50000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '1.00',
      ),
    ),
  ),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Combined on-screen thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks (Session Day) on Twitter/Facebook',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Other Title Partnership',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Small logo on Partners Page and rotating promo block on some pages',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'f7753eb0-af07-4b3c-9af4-416bf29c5c04',
);
  $products[] = array(
  'sku' => '2015_other_daycare',
  'title' => 'Daycare Partner',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => 'ee218b21-00d1-4ab4-ba32-98cc393ad6a7',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533937,
  'uuid' => 'b6d41141-d8c0-4e7a-81cc-bfdc8ee027c2',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 50000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '1.00',
      ),
    ),
  ),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Combined on-screen thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks (Session Day) on Twitter/Facebook',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Other Title Partnership',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Small logo on Partners Page and rotating promo block on some pages',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'f7753eb0-af07-4b3c-9af4-416bf29c5c04',
);
  $products[] = array(
  'sku' => '2015_tier_gold',
  'title' => 'Gold Partnership',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => '37e178f7-a6a4-49fd-a217-45d8001f9861',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533316,
  'uuid' => 'd6009009-36cb-4c27-9408-d462ddb78a9d',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 500000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '5.00',
      ),
    ),
  ),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Solo on-screen and combined verbal thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Recognition (via tweets, verbal, in program, and small signage) for coffee break food service',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Medium Table',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Large Logo, Inside Back Cover',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Large Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks - Saturday
Solo thanks (Session Day) and daily combined thanks on Twitter/Facebook
Medium Logo in the footer of every communication email',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Tier Partnership',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Large logo on Partners Page and footer promo on landing pages',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'f7753eb0-af07-4b3c-9af4-416bf29c5c04',
);
  $products[] = array(
  'sku' => '2015_tier_lead',
  'title' => 'Lead Partnership',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => '374a10cd-155b-4361-8d3d-7bc4d60267d2',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425531766,
  'uuid' => 'd7b20de7-5f61-4251-9003-775278b67a3b',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 800000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '3.00',
      ),
    ),
  ),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Solo verbal and on-screen thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Recognition (via tweets, verbal, in program, and small signage) for breakfast and lunch food service',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Large Table
Reservable Private Breakout Room',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'X-Large Logo, Inside Cover',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'X-Large Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Daily solo and combined thanks
Solo thanks (Saturday) and daily combined thanks
Daily combined thanks
Single combined thanks - Saturday',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Tier Partnership',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'X-Large logo on Partners Page and footer promo on all pages',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'f7753eb0-af07-4b3c-9af4-416bf29c5c04',
);
  $products[] = array(
  'sku' => '2015_other_coder_lounge',
  'title' => 'Chx Coder Lounge Partner',
  'status' => 1,
  'log' => '',
  'data' => FALSE,
  'vuuid' => 'a58928d8-c68a-47db-9a5b-fd3a3c495b1f',
  'type' => 'partnership',
  'language' => 'und',
  'created' => 1425533859,
  'uuid' => 'dcc059ec-fff7-4fc0-89a6-57145166ff82',
  'commerce_price' => array(
    'und' => array(
      0 => array(
        'amount' => 50000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'commerce_stock' => array(
    'und' => array(
      0 => array(
        'value' => '1.00',
      ),
    ),
  ),
  'field_prod_partnership_conf_yr' => array(
    'und' => array(
      0 => array(
        'target_id' => '881e207d-353a-4c88-99a9-64173cba2945',
        'uuid' => '881e207d-353a-4c88-99a9-64173cba2945',
      ),
    ),
  ),
  'field_prod_partnership_desc' => array(),
  'field_prod_partnership_image' => array(),
  'field_prod_partnership_job_fair' => array(
    'und' => array(
      0 => array(
        'value' => 'Participation in Job Fair with Table
Receives resumes for all job applicants',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_keynote' => array(
    'und' => array(
      0 => array(
        'value' => 'Combined on-screen thank you',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_other' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_pavilion' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_program' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_signage' => array(
    'und' => array(
      0 => array(
        'value' => 'Small Logo',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_social' => array(
    'und' => array(
      0 => array(
        'value' => 'Single combined thanks (Session Day) on Twitter/Facebook',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_swag' => array(
    'und' => array(
      0 => array(
        'value' => 'Not Applicable',
        'format' => NULL,
      ),
    ),
  ),
  'field_prod_partnership_type' => array(
    'und' => array(
      0 => array(
        'value' => 'Other Title Partnership',
      ),
    ),
  ),
  'field_prod_partnership_website' => array(
    'und' => array(
      0 => array(
        'value' => 'Small logo on Partners Page and rotating promo block on some pages',
        'format' => NULL,
      ),
    ),
  ),
  'rdf_mapping' => array(),
  'user_uuid' => 'f7753eb0-af07-4b3c-9af4-416bf29c5c04',
);
  return $products;
}
